version: '3.8'

services:
  backend:
    build: ./Bus-Ticket-Booking-System-BACKEND
    container_name: new_devops_backend
    ports:
      - "8070:8070"
    depends_on:
      - mongo

  frontend:
    build: ./Bus-ticket-Booking-System-Frontend
    container_name: new_devops_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'

volumes:
  mongo-data:
    driver: local
